### ISSUE TITLE
Error when enabling plugin on Linux ARM64

### ISSUE THREAD

**Issue by garro95** [rejetto/sharp#2]
Probably similar to #1, an error happens when enabling the plugin on linux-arm64:
```
Plugin sharp didn't start, with error: Something went wrong installing the "sharp" module Cannot find module '../build/Release/sharp-linuxmusl-arm64v8.node' Require stack: - /app/disk/plugins/sharp/node_modules/sharp/lib/sharp.js - /app/disk/plugins/sharp/node_modules/sharp/lib/constructor.js - /app/disk/plugins/sharp/node_modules/sharp/lib/index.js - /app/disk/plugins/sharp/plugin.js - /snapshot/hfs/dist/src/plugins.js - /snapshot/hfs/dist/src/api.get_file_list.js - /snapshot/hfs/dist/src/frontEndApis.js - /snapshot/hfs/dist/src/index.js 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath. Possible solutions: - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp" - Install for the current linuxmusl-arm64v8 runtime: "npm install --platform=linuxmusl --arch=arm64v8 sharp" - Consult the installation documentation: https://sharp.pixelplumbing.com/install Error: Something went wrong installing the "sharp" module
```

**Comment by rejetto** [comment]
the file i have is called "sharp-linux-arm64v8.node"
i totally miss that file.
If you get it I can consider adding it, but you need to test it's working well first.

i've spent a few minutes looking around, and i think support for linuxmusl was introduced only later.
this plugin of mine called "sharp" is actually just a wrapper for [sharp library](https://github.com/lovell/sharp).
i'm using 0.32, and maybe they introduced support in 0.33 .
updating doesn't seem trivial, tho, as they changed a few things and files are placed elsewhere.
one can do `npm install --force @img/sharp-linuxmusl-arm64`
but there's much work to do, i think most things must be done from scratch.
i'm not sure when i'll be able to this.
anyone is welcomed to do it.
you can consider using a linux that's not musl.

there is a little hope anyway: i cannot exclude that a file for version 0.33 will work with my 0.32, but i cannot test it, because i don't have linuxmusl.
[sharp-linuxmusl-arm64.node.zip](https://github.com/user-attachments/files/16736043/sharp-linuxmusl-arm64.node.zip)
if you want to try, this is the file from version 0.33 . The name is not arm64v8 but just arm64, so you will have to rename it and put it in the right folder.
If it works, i can add it.

**Comment by garro95** [comment]
Just for reference, what I am trying to do is adding the thumbnails plugin to hfs deployed on a raspberry pi using the docker container image.
i will look into that and see if I can workaround the issue. If I succeed, I will send a PR

**Comment by rejetto** [comment]
i just published an update for plugin rejetto/sharp that is supposed to add support for linuxmusl, but i couldn't test it myself.
let me know if it works for you.

**Comment by garro95** [comment]
@rejetto it did not start, but with a different error now:
```
Plugin sharp didn't start, with error: Something went wrong installing the "sharp" module Error loading shared library libstdc++.so.6: No such file or directory (needed by /app/disk/plugins/sharp/node_modules/sharp/build/Release/sharp-linuxmusl-arm64v8.node) Possible solutions: - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp" - Install for the current linuxmusl-arm64v8 runtime: "npm install --platform=linuxmusl --arch=arm64v8 sharp" - Consult the installation documentation: https://sharp.pixelplumbing.com/install Error: Something went wrong installing the "sharp" module
```
Probaly something's missing in the docker image

**Comment by rejetto** [comment]
ok, i will unpublish this update if it's not fixing.

**Comment by garro95** [comment]
The updated version worked after running `docker exec -u root -it hfs apk add libstdc++`

**Comment by garro95** [comment]
I created https://github.com/damienzonly/hfs-docker/pull/1 to fix the image

**Comment by rejetto** [comment]
mmm, this means i should republish the update, right?

**Comment by garro95** [comment]
Yes. Your update + installing libstdc++ on the container fixed the issue

**Comment by rejetto** [comment]
ok, done,  i now close this
